# Generated by Django 2.2.3 on 2019-09-26 07:21

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(max_length=255)),
                ('title_content', tinymce.models.HTMLField(default=None)),
                ('title', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1600, 900], upload_to='slider')),
            ],
        ),
    ]
