# Generated by Django 2.2.3 on 2019-09-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhet', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default=None, max_length=256)),
                ('twitter', models.CharField(default=None, max_length=256)),
                ('flickr', models.CharField(default=None, max_length=256)),
                ('linkedin', models.CharField(default=None, max_length=256)),
            ],
        ),
    ]
