# Generated by Django 2.2.3 on 2019-09-26 09:35

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhet', '0004_siteaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=255)),
                ('second_title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField(default=None)),
                ('image1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[400, 400], upload_to='about')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[400, 400], upload_to='about')),
                ('signature', models.ImageField(blank=True, upload_to='about')),
            ],
        ),
    ]
