# Generated by Django 2.2.3 on 2019-09-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhet', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=256)),
                ('content', models.TextField(default=None)),
                ('image', models.ImageField(default=None, upload_to='why_choose_us')),
            ],
        ),
    ]
