# Generated by Django 2.2.3 on 2019-09-26 11:12

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('skillhet', '0007_enquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=255)),
                ('second_title', models.CharField(max_length=255)),
                ('content', models.TextField(default=None)),
                ('small_content1', models.TextField(default=None)),
                ('small_content2', models.TextField(default=None)),
                ('small_content3', models.TextField(default=None)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[272, 300], upload_to='core_value')),
            ],
        ),
    ]
