# Generated by Django 2.2.3 on 2019-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhet', '0008_corevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquery',
            name='email',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='enquery',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enquery',
            name='mobile',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='enquery',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='enquery',
            name='subject',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
