# Generated by Django 2.2.3 on 2019-09-26 11:57

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhet', '0009_auto_20190926_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_content', tinymce.models.HTMLField(default=None)),
                ('slider_image1', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1000, 500], upload_to='post_details')),
                ('slider_image2', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1000, 500], upload_to='post_details')),
                ('slider_image3', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1000, 500], upload_to='post_details')),
                ('title1', models.CharField(max_length=255)),
                ('content1', tinymce.models.HTMLField(default=None)),
                ('image1', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[456, 286], upload_to='post_details')),
                ('title2', models.CharField(max_length=255)),
                ('content2', tinymce.models.HTMLField(default=None)),
                ('image2', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[456, 303], upload_to='post_details')),
                ('sub_title1', models.CharField(max_length=255)),
                ('sub_title2', models.CharField(max_length=255)),
                ('sub_title3', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skillhet.Category')),
            ],
        ),
    ]
