# Generated by Django 2.2.3 on 2019-09-26 12:43

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhet', '0010_postdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('title1', models.CharField(max_length=255)),
                ('content1', tinymce.models.HTMLField(default=None)),
                ('title2', models.CharField(max_length=255)),
                ('content2', tinymce.models.HTMLField(default=None)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[750, 750], upload_to='our_skill')),
            ],
        ),
    ]
