# Generated by Django 2.2.3 on 2019-09-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhet', '0011_ourskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourskill',
            name='content3',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='ourskill',
            name='title3',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourskill',
            name='content1',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='ourskill',
            name='content2',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='ourskill',
            name='heading',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourskill',
            name='title1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourskill',
            name='title2',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
